import { HttpClient } from '@angular/common/http';
import { inject, Injectable, OnDestroy } from '@angular/core';
import { catchError, concatMap, debounceTime, delay, filter, map, Observable, of, Subject, switchMap, tap, throwError } from 'rxjs';
import { GithubUserResponse, User } from '../interfaces';
import { GithubRepositoriesResponse } from '../interfaces/github-repositories-response.interface';


@Injectable({
  providedIn: 'root'
})
export class ProjectsService {


  private readonly API = 'https://api.github.com/users';
  private http = inject(HttpClient);


  // for testing only
  private fakeUserResponse = {
    "login": "juandavyc",
    "id": 129390499,
    "node_id": "U_kgDOB7ZXow",
    "avatar_url": "https://avatars.githubusercontent.com/u/129390499?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/juandavyc",
    "html_url": "https://github.com/juandavyc",
    "followers_url": "https://api.github.com/users/juandavyc/followers",
    "following_url": "https://api.github.com/users/juandavyc/following{/other_user}",
    "gists_url": "https://api.github.com/users/juandavyc/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/juandavyc/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/juandavyc/subscriptions",
    "organizations_url": "https://api.github.com/users/juandavyc/orgs",
    "repos_url": "https://api.github.com/users/juandavyc/repos",
    "events_url": "https://api.github.com/users/juandavyc/events{/privacy}",
    "received_events_url": "https://api.github.com/users/juandavyc/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false,
    "name": "Juan Yara Cifuentes",
    "company": "Full Stack Developer",
    "blog": "juan.deimosdev.com",
    "location": "Colombia, Bogotá DC",
    "email": null,
    "hireable": null,
    "bio": "<bad-ape [says]=\"Oh noo\"/>",
    "twitter_username": null,
    "public_repos": 21,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2023-03-30T11:24:59Z",
    "updated_at": "2024-11-14T18:14:25Z"
  };
  //

  private fakeUserResponseError = {
    message: "Not Found",
    documentation_url: "https://docs.github.com/rest",
    status: "404"
  }

  private fakeRepositoriesResponse = [
    {
      "id": 516008072,
      "node_id": "R_kgDOHsGoiA",
      "name": "-nest-teslo-shop-front",
      "full_name": "Klerith/-nest-teslo-shop-front",
      "private": false,
      "owner": {
        "login": "Klerith",
        "id": 3438503,
        "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Klerith",
        "html_url": "https://github.com/Klerith",
        "followers_url": "https://api.github.com/users/Klerith/followers",
        "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
        "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
        "organizations_url": "https://api.github.com/users/Klerith/orgs",
        "repos_url": "https://api.github.com/users/Klerith/repos",
        "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Klerith/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/Klerith/-nest-teslo-shop-front",
      "description": "Aplicación de Frontend para conectar websockets con Nest",
      "fork": false,
      "url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front",
      "forks_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/forks",
      "keys_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/teams",
      "hooks_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/hooks",
      "issue_events_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/events",
      "assignees_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/tags",
      "blobs_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/languages",
      "stargazers_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/stargazers",
      "contributors_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/contributors",
      "subscribers_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/subscribers",
      "subscription_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/subscription",
      "commits_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/merges",
      "archive_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/downloads",
      "issues_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/labels{/name}",
      "releases_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Klerith/-nest-teslo-shop-front/deployments",
      "created_at": "2022-07-20T14:09:56Z",
      "updated_at": "2024-11-16T13:52:15Z",
      "pushed_at": "2022-07-20T14:10:29Z",
      "git_url": "git://github.com/Klerith/-nest-teslo-shop-front.git",
      "ssh_url": "git@github.com:Klerith/-nest-teslo-shop-front.git",
      "clone_url": "https://github.com/Klerith/-nest-teslo-shop-front.git",
      "svn_url": "https://github.com/Klerith/-nest-teslo-shop-front",
      "homepage": null,
      "size": 11,
      "stargazers_count": 6,
      "watchers_count": 6,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 3,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 3,
      "open_issues": 0,
      "watchers": 6,
      "default_branch": "main"
    },
    {
      "id": 276690425,
      "node_id": "MDEwOlJlcG9zaXRvcnkyNzY2OTA0MjU=",
      "name": "admin-pro-backend",
      "full_name": "Klerith/admin-pro-backend",
      "private": false,
      "owner": {
        "login": "Klerith",
        "id": 3438503,
        "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Klerith",
        "html_url": "https://github.com/Klerith",
        "followers_url": "https://api.github.com/users/Klerith/followers",
        "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
        "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
        "organizations_url": "https://api.github.com/users/Klerith/orgs",
        "repos_url": "https://api.github.com/users/Klerith/repos",
        "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Klerith/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/Klerith/admin-pro-backend",
      "description": "Este es el repositorio de mi curso de Angular Avanzado - Backend",
      "fork": false,
      "url": "https://api.github.com/repos/Klerith/admin-pro-backend",
      "forks_url": "https://api.github.com/repos/Klerith/admin-pro-backend/forks",
      "keys_url": "https://api.github.com/repos/Klerith/admin-pro-backend/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Klerith/admin-pro-backend/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Klerith/admin-pro-backend/teams",
      "hooks_url": "https://api.github.com/repos/Klerith/admin-pro-backend/hooks",
      "issue_events_url": "https://api.github.com/repos/Klerith/admin-pro-backend/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Klerith/admin-pro-backend/events",
      "assignees_url": "https://api.github.com/repos/Klerith/admin-pro-backend/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Klerith/admin-pro-backend/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Klerith/admin-pro-backend/tags",
      "blobs_url": "https://api.github.com/repos/Klerith/admin-pro-backend/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Klerith/admin-pro-backend/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Klerith/admin-pro-backend/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Klerith/admin-pro-backend/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Klerith/admin-pro-backend/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Klerith/admin-pro-backend/languages",
      "stargazers_url": "https://api.github.com/repos/Klerith/admin-pro-backend/stargazers",
      "contributors_url": "https://api.github.com/repos/Klerith/admin-pro-backend/contributors",
      "subscribers_url": "https://api.github.com/repos/Klerith/admin-pro-backend/subscribers",
      "subscription_url": "https://api.github.com/repos/Klerith/admin-pro-backend/subscription",
      "commits_url": "https://api.github.com/repos/Klerith/admin-pro-backend/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Klerith/admin-pro-backend/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Klerith/admin-pro-backend/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Klerith/admin-pro-backend/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Klerith/admin-pro-backend/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Klerith/admin-pro-backend/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Klerith/admin-pro-backend/merges",
      "archive_url": "https://api.github.com/repos/Klerith/admin-pro-backend/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Klerith/admin-pro-backend/downloads",
      "issues_url": "https://api.github.com/repos/Klerith/admin-pro-backend/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Klerith/admin-pro-backend/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Klerith/admin-pro-backend/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Klerith/admin-pro-backend/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Klerith/admin-pro-backend/labels{/name}",
      "releases_url": "https://api.github.com/repos/Klerith/admin-pro-backend/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Klerith/admin-pro-backend/deployments",
      "created_at": "2020-07-02T16:04:13Z",
      "updated_at": "2024-11-15T13:10:20Z",
      "pushed_at": "2022-12-22T17:18:03Z",
      "git_url": "git://github.com/Klerith/admin-pro-backend.git",
      "ssh_url": "git@github.com:Klerith/admin-pro-backend.git",
      "clone_url": "https://github.com/Klerith/admin-pro-backend.git",
      "svn_url": "https://github.com/Klerith/admin-pro-backend",
      "homepage": null,
      "size": 18728,
      "stargazers_count": 28,
      "watchers_count": 28,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 10,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 8,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 10,
      "open_issues": 8,
      "watchers": 28,
      "default_branch": "master"
    },
    {
      "id": 109708478,
      "node_id": "MDEwOlJlcG9zaXRvcnkxMDk3MDg0Nzg=",
      "name": "admipro-udemy",
      "full_name": "Klerith/admipro-udemy",
      "private": false,
      "owner": {
        "login": "Klerith",
        "id": 3438503,
        "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Klerith",
        "html_url": "https://github.com/Klerith",
        "followers_url": "https://api.github.com/users/Klerith/followers",
        "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
        "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
        "organizations_url": "https://api.github.com/users/Klerith/orgs",
        "repos_url": "https://api.github.com/users/Klerith/repos",
        "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Klerith/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/Klerith/admipro-udemy",
      "description": "Este es el demo que estamos trabajando para el curso",
      "fork": false,
      "url": "https://api.github.com/repos/Klerith/admipro-udemy",
      "forks_url": "https://api.github.com/repos/Klerith/admipro-udemy/forks",
      "keys_url": "https://api.github.com/repos/Klerith/admipro-udemy/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Klerith/admipro-udemy/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Klerith/admipro-udemy/teams",
      "hooks_url": "https://api.github.com/repos/Klerith/admipro-udemy/hooks",
      "issue_events_url": "https://api.github.com/repos/Klerith/admipro-udemy/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Klerith/admipro-udemy/events",
      "assignees_url": "https://api.github.com/repos/Klerith/admipro-udemy/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Klerith/admipro-udemy/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Klerith/admipro-udemy/tags",
      "blobs_url": "https://api.github.com/repos/Klerith/admipro-udemy/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Klerith/admipro-udemy/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Klerith/admipro-udemy/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Klerith/admipro-udemy/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Klerith/admipro-udemy/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Klerith/admipro-udemy/languages",
      "stargazers_url": "https://api.github.com/repos/Klerith/admipro-udemy/stargazers",
      "contributors_url": "https://api.github.com/repos/Klerith/admipro-udemy/contributors",
      "subscribers_url": "https://api.github.com/repos/Klerith/admipro-udemy/subscribers",
      "subscription_url": "https://api.github.com/repos/Klerith/admipro-udemy/subscription",
      "commits_url": "https://api.github.com/repos/Klerith/admipro-udemy/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Klerith/admipro-udemy/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Klerith/admipro-udemy/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Klerith/admipro-udemy/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Klerith/admipro-udemy/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Klerith/admipro-udemy/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Klerith/admipro-udemy/merges",
      "archive_url": "https://api.github.com/repos/Klerith/admipro-udemy/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Klerith/admipro-udemy/downloads",
      "issues_url": "https://api.github.com/repos/Klerith/admipro-udemy/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Klerith/admipro-udemy/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Klerith/admipro-udemy/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Klerith/admipro-udemy/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Klerith/admipro-udemy/labels{/name}",
      "releases_url": "https://api.github.com/repos/Klerith/admipro-udemy/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Klerith/admipro-udemy/deployments",
      "created_at": "2017-11-06T14:50:21Z",
      "updated_at": "2024-11-14T21:46:21Z",
      "pushed_at": "2020-04-20T01:53:12Z",
      "git_url": "git://github.com/Klerith/admipro-udemy.git",
      "ssh_url": "git@github.com:Klerith/admipro-udemy.git",
      "clone_url": "https://github.com/Klerith/admipro-udemy.git",
      "svn_url": "https://github.com/Klerith/admipro-udemy",
      "homepage": null,
      "size": 6163,
      "stargazers_count": 29,
      "watchers_count": 29,
      "language": "CSS",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 30,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 1,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 30,
      "open_issues": 1,
      "watchers": 29,
      "default_branch": "master"
    },
    {
      "id": 94481226,
      "node_id": "MDEwOlJlcG9zaXRvcnk5NDQ4MTIyNg==",
      "name": "agm-demomap",
      "full_name": "Klerith/agm-demomap",
      "private": false,
      "owner": {
        "login": "Klerith",
        "id": 3438503,
        "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Klerith",
        "html_url": "https://github.com/Klerith",
        "followers_url": "https://api.github.com/users/Klerith/followers",
        "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
        "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
        "organizations_url": "https://api.github.com/users/Klerith/orgs",
        "repos_url": "https://api.github.com/users/Klerith/repos",
        "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Klerith/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/Klerith/agm-demomap",
      "description": null,
      "fork": false,
      "url": "https://api.github.com/repos/Klerith/agm-demomap",
      "forks_url": "https://api.github.com/repos/Klerith/agm-demomap/forks",
      "keys_url": "https://api.github.com/repos/Klerith/agm-demomap/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Klerith/agm-demomap/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Klerith/agm-demomap/teams",
      "hooks_url": "https://api.github.com/repos/Klerith/agm-demomap/hooks",
      "issue_events_url": "https://api.github.com/repos/Klerith/agm-demomap/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Klerith/agm-demomap/events",
      "assignees_url": "https://api.github.com/repos/Klerith/agm-demomap/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Klerith/agm-demomap/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Klerith/agm-demomap/tags",
      "blobs_url": "https://api.github.com/repos/Klerith/agm-demomap/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Klerith/agm-demomap/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Klerith/agm-demomap/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Klerith/agm-demomap/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Klerith/agm-demomap/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Klerith/agm-demomap/languages",
      "stargazers_url": "https://api.github.com/repos/Klerith/agm-demomap/stargazers",
      "contributors_url": "https://api.github.com/repos/Klerith/agm-demomap/contributors",
      "subscribers_url": "https://api.github.com/repos/Klerith/agm-demomap/subscribers",
      "subscription_url": "https://api.github.com/repos/Klerith/agm-demomap/subscription",
      "commits_url": "https://api.github.com/repos/Klerith/agm-demomap/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Klerith/agm-demomap/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Klerith/agm-demomap/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Klerith/agm-demomap/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Klerith/agm-demomap/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Klerith/agm-demomap/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Klerith/agm-demomap/merges",
      "archive_url": "https://api.github.com/repos/Klerith/agm-demomap/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Klerith/agm-demomap/downloads",
      "issues_url": "https://api.github.com/repos/Klerith/agm-demomap/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Klerith/agm-demomap/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Klerith/agm-demomap/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Klerith/agm-demomap/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Klerith/agm-demomap/labels{/name}",
      "releases_url": "https://api.github.com/repos/Klerith/agm-demomap/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Klerith/agm-demomap/deployments",
      "created_at": "2017-06-15T21:45:04Z",
      "updated_at": "2017-06-15T21:51:49Z",
      "pushed_at": "2017-06-15T21:55:53Z",
      "git_url": "git://github.com/Klerith/agm-demomap.git",
      "ssh_url": "git@github.com:Klerith/agm-demomap.git",
      "clone_url": "https://github.com/Klerith/agm-demomap.git",
      "svn_url": "https://github.com/Klerith/agm-demomap",
      "homepage": null,
      "size": 1933,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "CSS",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "master"
    },
    {
      "id": 296748307,
      "node_id": "MDEwOlJlcG9zaXRvcnkyOTY3NDgzMDc=",
      "name": "algonquin-php-intro",
      "full_name": "Klerith/algonquin-php-intro",
      "private": false,
      "owner": {
        "login": "Klerith",
        "id": 3438503,
        "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Klerith",
        "html_url": "https://github.com/Klerith",
        "followers_url": "https://api.github.com/users/Klerith/followers",
        "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
        "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
        "organizations_url": "https://api.github.com/users/Klerith/orgs",
        "repos_url": "https://api.github.com/users/Klerith/repos",
        "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Klerith/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/Klerith/algonquin-php-intro",
      "description": null,
      "fork": false,
      "url": "https://api.github.com/repos/Klerith/algonquin-php-intro",
      "forks_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/forks",
      "keys_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/teams",
      "hooks_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/hooks",
      "issue_events_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/events",
      "assignees_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/tags",
      "blobs_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/languages",
      "stargazers_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/stargazers",
      "contributors_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/contributors",
      "subscribers_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/subscribers",
      "subscription_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/subscription",
      "commits_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/merges",
      "archive_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/downloads",
      "issues_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/labels{/name}",
      "releases_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Klerith/algonquin-php-intro/deployments",
      "created_at": "2020-09-18T23:19:54Z",
      "updated_at": "2024-08-15T09:05:47Z",
      "pushed_at": "2020-09-18T23:21:40Z",
      "git_url": "git://github.com/Klerith/algonquin-php-intro.git",
      "ssh_url": "git@github.com:Klerith/algonquin-php-intro.git",
      "clone_url": "https://github.com/Klerith/algonquin-php-intro.git",
      "svn_url": "https://github.com/Klerith/algonquin-php-intro",
      "homepage": null,
      "size": 2,
      "stargazers_count": 3,
      "watchers_count": 3,
      "language": "PHP",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 3,
      "default_branch": "master"
    },
    {
      "id": 98802176,
      "node_id": "MDEwOlJlcG9zaXRvcnk5ODgwMjE3Ng==",
      "name": "angular-1-6-routes",
      "full_name": "Klerith/angular-1-6-routes",
      "private": false,
      "owner": {
        "login": "Klerith",
        "id": 3438503,
        "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Klerith",
        "html_url": "https://github.com/Klerith",
        "followers_url": "https://api.github.com/users/Klerith/followers",
        "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
        "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
        "organizations_url": "https://api.github.com/users/Klerith/orgs",
        "repos_url": "https://api.github.com/users/Klerith/repos",
        "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Klerith/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/Klerith/angular-1-6-routes",
      "description": "Este es un pequeño ejemplo de las rutas funcionando",
      "fork": false,
      "url": "https://api.github.com/repos/Klerith/angular-1-6-routes",
      "forks_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/forks",
      "keys_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/teams",
      "hooks_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/hooks",
      "issue_events_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/events",
      "assignees_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/tags",
      "blobs_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/languages",
      "stargazers_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/stargazers",
      "contributors_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/contributors",
      "subscribers_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/subscribers",
      "subscription_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/subscription",
      "commits_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/merges",
      "archive_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/downloads",
      "issues_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/labels{/name}",
      "releases_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Klerith/angular-1-6-routes/deployments",
      "created_at": "2017-07-30T14:16:33Z",
      "updated_at": "2018-11-17T22:15:12Z",
      "pushed_at": "2017-07-30T14:19:53Z",
      "git_url": "git://github.com/Klerith/angular-1-6-routes.git",
      "ssh_url": "git@github.com:Klerith/angular-1-6-routes.git",
      "clone_url": "https://github.com/Klerith/angular-1-6-routes.git",
      "svn_url": "https://github.com/Klerith/angular-1-6-routes",
      "homepage": null,
      "size": 265,
      "stargazers_count": 1,
      "watchers_count": 1,
      "language": "HTML",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 1,
      "default_branch": "master"
    },
    {
      "id": 274482095,
      "node_id": "MDEwOlJlcG9zaXRvcnkyNzQ0ODIwOTU=",
      "name": "angular-adv-adminpro",
      "full_name": "Klerith/angular-adv-adminpro",
      "private": false,
      "owner": {
        "login": "Klerith",
        "id": 3438503,
        "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Klerith",
        "html_url": "https://github.com/Klerith",
        "followers_url": "https://api.github.com/users/Klerith/followers",
        "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
        "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
        "organizations_url": "https://api.github.com/users/Klerith/orgs",
        "repos_url": "https://api.github.com/users/Klerith/repos",
        "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Klerith/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/Klerith/angular-adv-adminpro",
      "description": "Repositorio del curso de Angular Avanzado de Fernando",
      "fork": false,
      "url": "https://api.github.com/repos/Klerith/angular-adv-adminpro",
      "forks_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/forks",
      "keys_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/teams",
      "hooks_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/hooks",
      "issue_events_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/events",
      "assignees_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/tags",
      "blobs_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/languages",
      "stargazers_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/stargazers",
      "contributors_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/contributors",
      "subscribers_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/subscribers",
      "subscription_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/subscription",
      "commits_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/merges",
      "archive_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/downloads",
      "issues_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/labels{/name}",
      "releases_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Klerith/angular-adv-adminpro/deployments",
      "created_at": "2020-06-23T18:40:16Z",
      "updated_at": "2024-10-12T02:40:11Z",
      "pushed_at": "2023-10-11T04:29:36Z",
      "git_url": "git://github.com/Klerith/angular-adv-adminpro.git",
      "ssh_url": "git@github.com:Klerith/angular-adv-adminpro.git",
      "clone_url": "https://github.com/Klerith/angular-adv-adminpro.git",
      "svn_url": "https://github.com/Klerith/angular-adv-adminpro",
      "homepage": null,
      "size": 19251,
      "stargazers_count": 25,
      "watchers_count": 25,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 23,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 6,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 23,
      "open_issues": 6,
      "watchers": 25,
      "default_branch": "master"
    },
    {
      "id": 274216284,
      "node_id": "MDEwOlJlcG9zaXRvcnkyNzQyMTYyODQ=",
      "name": "angular-adv-tarea-01",
      "full_name": "Klerith/angular-adv-tarea-01",
      "private": false,
      "owner": {
        "login": "Klerith",
        "id": 3438503,
        "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Klerith",
        "html_url": "https://github.com/Klerith",
        "followers_url": "https://api.github.com/users/Klerith/followers",
        "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
        "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
        "organizations_url": "https://api.github.com/users/Klerith/orgs",
        "repos_url": "https://api.github.com/users/Klerith/repos",
        "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Klerith/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/Klerith/angular-adv-tarea-01",
      "description": "Repositorio de una tarea de Angular",
      "fork": false,
      "url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01",
      "forks_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/forks",
      "keys_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/teams",
      "hooks_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/hooks",
      "issue_events_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/events",
      "assignees_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/tags",
      "blobs_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/languages",
      "stargazers_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/stargazers",
      "contributors_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/contributors",
      "subscribers_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/subscribers",
      "subscription_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/subscription",
      "commits_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/merges",
      "archive_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/downloads",
      "issues_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/labels{/name}",
      "releases_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Klerith/angular-adv-tarea-01/deployments",
      "created_at": "2020-06-22T18:42:45Z",
      "updated_at": "2024-01-04T22:52:54Z",
      "pushed_at": "2023-10-11T06:47:39Z",
      "git_url": "git://github.com/Klerith/angular-adv-tarea-01.git",
      "ssh_url": "git@github.com:Klerith/angular-adv-tarea-01.git",
      "clone_url": "https://github.com/Klerith/angular-adv-tarea-01.git",
      "svn_url": "https://github.com/Klerith/angular-adv-tarea-01",
      "homepage": null,
      "size": 1346,
      "stargazers_count": 5,
      "watchers_count": 5,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 12,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 10,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 12,
      "open_issues": 10,
      "watchers": 5,
      "default_branch": "master"
    },
    {
      "id": 331160643,
      "node_id": "MDEwOlJlcG9zaXRvcnkzMzExNjA2NDM=",
      "name": "angular-auth-mean",
      "full_name": "Klerith/angular-auth-mean",
      "private": false,
      "owner": {
        "login": "Klerith",
        "id": 3438503,
        "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Klerith",
        "html_url": "https://github.com/Klerith",
        "followers_url": "https://api.github.com/users/Klerith/followers",
        "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
        "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
        "organizations_url": "https://api.github.com/users/Klerith/orgs",
        "repos_url": "https://api.github.com/users/Klerith/repos",
        "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Klerith/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/Klerith/angular-auth-mean",
      "description": "Curso de Angular de cero a experto - MEAN Auth",
      "fork": false,
      "url": "https://api.github.com/repos/Klerith/angular-auth-mean",
      "forks_url": "https://api.github.com/repos/Klerith/angular-auth-mean/forks",
      "keys_url": "https://api.github.com/repos/Klerith/angular-auth-mean/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Klerith/angular-auth-mean/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Klerith/angular-auth-mean/teams",
      "hooks_url": "https://api.github.com/repos/Klerith/angular-auth-mean/hooks",
      "issue_events_url": "https://api.github.com/repos/Klerith/angular-auth-mean/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Klerith/angular-auth-mean/events",
      "assignees_url": "https://api.github.com/repos/Klerith/angular-auth-mean/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Klerith/angular-auth-mean/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Klerith/angular-auth-mean/tags",
      "blobs_url": "https://api.github.com/repos/Klerith/angular-auth-mean/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Klerith/angular-auth-mean/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Klerith/angular-auth-mean/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Klerith/angular-auth-mean/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Klerith/angular-auth-mean/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Klerith/angular-auth-mean/languages",
      "stargazers_url": "https://api.github.com/repos/Klerith/angular-auth-mean/stargazers",
      "contributors_url": "https://api.github.com/repos/Klerith/angular-auth-mean/contributors",
      "subscribers_url": "https://api.github.com/repos/Klerith/angular-auth-mean/subscribers",
      "subscription_url": "https://api.github.com/repos/Klerith/angular-auth-mean/subscription",
      "commits_url": "https://api.github.com/repos/Klerith/angular-auth-mean/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Klerith/angular-auth-mean/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Klerith/angular-auth-mean/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Klerith/angular-auth-mean/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Klerith/angular-auth-mean/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Klerith/angular-auth-mean/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Klerith/angular-auth-mean/merges",
      "archive_url": "https://api.github.com/repos/Klerith/angular-auth-mean/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Klerith/angular-auth-mean/downloads",
      "issues_url": "https://api.github.com/repos/Klerith/angular-auth-mean/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Klerith/angular-auth-mean/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Klerith/angular-auth-mean/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Klerith/angular-auth-mean/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Klerith/angular-auth-mean/labels{/name}",
      "releases_url": "https://api.github.com/repos/Klerith/angular-auth-mean/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Klerith/angular-auth-mean/deployments",
      "created_at": "2021-01-20T01:43:54Z",
      "updated_at": "2023-05-28T23:51:42Z",
      "pushed_at": "2021-01-20T23:56:30Z",
      "git_url": "git://github.com/Klerith/angular-auth-mean.git",
      "ssh_url": "git@github.com:Klerith/angular-auth-mean.git",
      "clone_url": "https://github.com/Klerith/angular-auth-mean.git",
      "svn_url": "https://github.com/Klerith/angular-auth-mean",
      "homepage": null,
      "size": 2341,
      "stargazers_count": 2,
      "watchers_count": 2,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 2,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 2,
      "open_issues": 0,
      "watchers": 2,
      "default_branch": "main"
    },
    {
      "id": 204997682,
      "node_id": "MDEwOlJlcG9zaXRvcnkyMDQ5OTc2ODI=",
      "name": "angular-auth0",
      "full_name": "Klerith/angular-auth0",
      "private": false,
      "owner": {
        "login": "Klerith",
        "id": 3438503,
        "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Klerith",
        "html_url": "https://github.com/Klerith",
        "followers_url": "https://api.github.com/users/Klerith/followers",
        "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
        "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
        "organizations_url": "https://api.github.com/users/Klerith/orgs",
        "repos_url": "https://api.github.com/users/Klerith/repos",
        "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Klerith/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
      },
      "html_url": "https://github.com/Klerith/angular-auth0",
      "description": "Actualización de la sección de Auth0 del curso de Angular de cero a experto.",
      "fork": false,
      "url": "https://api.github.com/repos/Klerith/angular-auth0",
      "forks_url": "https://api.github.com/repos/Klerith/angular-auth0/forks",
      "keys_url": "https://api.github.com/repos/Klerith/angular-auth0/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/Klerith/angular-auth0/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/Klerith/angular-auth0/teams",
      "hooks_url": "https://api.github.com/repos/Klerith/angular-auth0/hooks",
      "issue_events_url": "https://api.github.com/repos/Klerith/angular-auth0/issues/events{/number}",
      "events_url": "https://api.github.com/repos/Klerith/angular-auth0/events",
      "assignees_url": "https://api.github.com/repos/Klerith/angular-auth0/assignees{/user}",
      "branches_url": "https://api.github.com/repos/Klerith/angular-auth0/branches{/branch}",
      "tags_url": "https://api.github.com/repos/Klerith/angular-auth0/tags",
      "blobs_url": "https://api.github.com/repos/Klerith/angular-auth0/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/Klerith/angular-auth0/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/Klerith/angular-auth0/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/Klerith/angular-auth0/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/Klerith/angular-auth0/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/Klerith/angular-auth0/languages",
      "stargazers_url": "https://api.github.com/repos/Klerith/angular-auth0/stargazers",
      "contributors_url": "https://api.github.com/repos/Klerith/angular-auth0/contributors",
      "subscribers_url": "https://api.github.com/repos/Klerith/angular-auth0/subscribers",
      "subscription_url": "https://api.github.com/repos/Klerith/angular-auth0/subscription",
      "commits_url": "https://api.github.com/repos/Klerith/angular-auth0/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/Klerith/angular-auth0/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/Klerith/angular-auth0/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/Klerith/angular-auth0/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/Klerith/angular-auth0/contents/{+path}",
      "compare_url": "https://api.github.com/repos/Klerith/angular-auth0/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/Klerith/angular-auth0/merges",
      "archive_url": "https://api.github.com/repos/Klerith/angular-auth0/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/Klerith/angular-auth0/downloads",
      "issues_url": "https://api.github.com/repos/Klerith/angular-auth0/issues{/number}",
      "pulls_url": "https://api.github.com/repos/Klerith/angular-auth0/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/Klerith/angular-auth0/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/Klerith/angular-auth0/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/Klerith/angular-auth0/labels{/name}",
      "releases_url": "https://api.github.com/repos/Klerith/angular-auth0/releases{/id}",
      "deployments_url": "https://api.github.com/repos/Klerith/angular-auth0/deployments",
      "created_at": "2019-08-28T18:29:12Z",
      "updated_at": "2024-09-03T17:42:48Z",
      "pushed_at": "2023-01-07T09:10:01Z",
      "git_url": "git://github.com/Klerith/angular-auth0.git",
      "ssh_url": "git@github.com:Klerith/angular-auth0.git",
      "clone_url": "https://github.com/Klerith/angular-auth0.git",
      "svn_url": "https://github.com/Klerith/angular-auth0",
      "homepage": null,
      "size": 2090,
      "stargazers_count": 12,
      "watchers_count": 12,
      "language": "TypeScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "has_discussions": false,
      "forks_count": 10,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 27,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "web_commit_signoff_required": false,
      "topics": [],
      "visibility": "public",
      "forks": 10,
      "open_issues": 27,
      "watchers": 12,
      "default_branch": "master"
    }
  ]


  public loadRepositories(userName: string, page: number): Observable<GithubRepositoriesResponse[]> {
    // return new Observable<GithubRepositoriesResponse[]>((subs) => {
    //   //subs.error(this.fakeUserResponseErrsaxcsadsdarefor);
    //   subs.next(this.fakeRepositoriesResponse);
    //   subs.complete();
    // }).pipe(
    //   //filter((repositories)=> !!repositories),
    //   catchError((error) => {
    //     return of([]);
    //   })
    // )
    const url = `${this.API}/${userName}/repos?page=${page}&per_page=8&sort=stars&order=desc`;
    return this.http.get<GithubRepositoriesResponse[]>(url)
    .pipe(
      catchError((error)=>{
        return throwError(()=> new Error(error));
      })
    )
  }

  public loadUser(userName: string): Observable<User | null> {

    return new Observable<GithubUserResponse>((subs) => {
      //subs.error(this.fakeUserResponseError);
      subs.next(this.fakeUserResponse);
      subs.complete();
    }).pipe(
      map(({
        login, id, avatar_url, html_url, repos_url, events_url,
        received_events_url, name, company, blog,
        location, bio, twitter_username, public_repos
      }) => ({
        login, id, avatar_url, html_url, repos_url, events_url,
        received_events_url, name, company, blog,
        location, bio, twitter_username, public_repos
      })),

      catchError((error) => {
       // console.error(error)
        return of(null)
      })
    )

    // return this.http.get<GithubUserResponse>(`${this.API}/${userName}`)
    //   .pipe(
    //     map(({
    //       login, id, avatar_url, html_url, repos_url, events_url,
    //       received_events_url, name, company, blog,
    //       location, bio, twitter_username, public_repos
    //     }) => ({
    //       login, id, avatar_url, html_url, repos_url, events_url,
    //       received_events_url, name, company, blog,
    //       location, bio, twitter_username, public_repos
    //     })
    //     ),
    //     catchError((error) => {
    //       return of(null)
    //     })
    //   );
  }
}
