import { HttpClient } from '@angular/common/http';
import { effect, inject, Injectable, OnDestroy } from '@angular/core';
import { catchError, concatMap, debounceTime, delay, filter, map, Observable, of, Subject, switchMap, tap, throwError } from 'rxjs';
import { GithubUserResponse, User } from '../interfaces';
import { GithubRepositoriesResponse, Item } from '../interfaces/github-repositories-response.interface';
import { RepositoriesFilterService } from './repositories-filter.service';


@Injectable({
  providedIn: 'root'
})
export class ProjectsService {


  private readonly API = 'https://api.github.com';
  private http = inject(HttpClient);


  //private service = inject(RepositoriesFilterService)

  // for testing only
  private fakeUserResponse = {
    "login": "juandavyc",
    "id": 129390499,
    "node_id": "U_kgDOB7ZXow",
    "avatar_url": "https://avatars.githubusercontent.com/u/129390499?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/juandavyc",
    "html_url": "https://github.com/juandavyc",
    "followers_url": "https://api.github.com/users/juandavyc/followers",
    "following_url": "https://api.github.com/users/juandavyc/following{/other_user}",
    "gists_url": "https://api.github.com/users/juandavyc/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/juandavyc/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/juandavyc/subscriptions",
    "organizations_url": "https://api.github.com/users/juandavyc/orgs",
    "repos_url": "https://api.github.com/users/juandavyc/repos",
    "events_url": "https://api.github.com/users/juandavyc/events{/privacy}",
    "received_events_url": "https://api.github.com/users/juandavyc/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false,
    "name": "Juan Yara Cifuentes",
    "company": "Full Stack Developer",
    "blog": "juan.deimosdev.com",
    "location": "Colombia, Bogotá DC",
    "email": null,
    "hireable": null,
    "bio": "<bad-ape [says]=\"Oh noo\"/>",
    "twitter_username": null,
    "public_repos": 21,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2023-03-30T11:24:59Z",
    "updated_at": "2024-11-14T18:14:25Z"
  };
  //

  private fakeUserResponseError = {
    message: "Not Found",
    documentation_url: "https://docs.github.com/rest",
    status: "404"
  }

  private fakeRepositoriesResponse = {
    total_count: 443,
    incomplete_results: false,
    items: [
      {
        "id": 241421778,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNDE0MjE3Nzg=",
        "name": "animate_do_package",
        "full_name": "Klerith/animate_do_package",
        "private": false,
        "owner": {
          "login": "Klerith",
          "id": 3438503,
          "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Klerith",
          "html_url": "https://github.com/Klerith",
          "followers_url": "https://api.github.com/users/Klerith/followers",
          "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
          "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
          "organizations_url": "https://api.github.com/users/Klerith/orgs",
          "repos_url": "https://api.github.com/users/Klerith/repos",
          "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Klerith/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Klerith/animate_do_package",
        "description": "Animate_do Package",
        "fork": false,
        "url": "https://api.github.com/repos/Klerith/animate_do_package",
        "forks_url": "https://api.github.com/repos/Klerith/animate_do_package/forks",
        "keys_url": "https://api.github.com/repos/Klerith/animate_do_package/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Klerith/animate_do_package/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Klerith/animate_do_package/teams",
        "hooks_url": "https://api.github.com/repos/Klerith/animate_do_package/hooks",
        "issue_events_url": "https://api.github.com/repos/Klerith/animate_do_package/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Klerith/animate_do_package/events",
        "assignees_url": "https://api.github.com/repos/Klerith/animate_do_package/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Klerith/animate_do_package/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Klerith/animate_do_package/tags",
        "blobs_url": "https://api.github.com/repos/Klerith/animate_do_package/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Klerith/animate_do_package/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Klerith/animate_do_package/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Klerith/animate_do_package/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Klerith/animate_do_package/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Klerith/animate_do_package/languages",
        "stargazers_url": "https://api.github.com/repos/Klerith/animate_do_package/stargazers",
        "contributors_url": "https://api.github.com/repos/Klerith/animate_do_package/contributors",
        "subscribers_url": "https://api.github.com/repos/Klerith/animate_do_package/subscribers",
        "subscription_url": "https://api.github.com/repos/Klerith/animate_do_package/subscription",
        "commits_url": "https://api.github.com/repos/Klerith/animate_do_package/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Klerith/animate_do_package/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Klerith/animate_do_package/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Klerith/animate_do_package/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Klerith/animate_do_package/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Klerith/animate_do_package/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Klerith/animate_do_package/merges",
        "archive_url": "https://api.github.com/repos/Klerith/animate_do_package/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Klerith/animate_do_package/downloads",
        "issues_url": "https://api.github.com/repos/Klerith/animate_do_package/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Klerith/animate_do_package/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Klerith/animate_do_package/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Klerith/animate_do_package/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Klerith/animate_do_package/labels{/name}",
        "releases_url": "https://api.github.com/repos/Klerith/animate_do_package/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Klerith/animate_do_package/deployments",
        "created_at": "2020-02-18T17:18:07Z",
        "updated_at": "2024-11-25T18:21:20Z",
        "pushed_at": "2024-03-05T21:45:09Z",
        "git_url": "git://github.com/Klerith/animate_do_package.git",
        "ssh_url": "git@github.com:Klerith/animate_do_package.git",
        "clone_url": "https://github.com/Klerith/animate_do_package.git",
        "svn_url": "https://github.com/Klerith/animate_do_package",
        "homepage": "https://pub.dev/packages/animate_do",
        "size": 6410,
        "stargazers_count": 308,
        "watchers_count": 308,
        "language": "Dart",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 37,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 5,
        "license": {
          "key": "mit",
          "name": "MIT License",
          "spdx_id": "MIT",
          "url": "https://api.github.com/licenses/mit",
          "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "animations",
          "dart",
          "fernandoherrera",
          "flutter"
        ],
        "visibility": "public",
        "forks": 37,
        "open_issues": 5,
        "watchers": 308,
        "default_branch": "master",
        "score": 1.0
      },
      {
        "id": 665656140,
        "node_id": "R_kgDOJ60bTA",
        "name": "mas-talento",
        "full_name": "Klerith/mas-talento",
        "private": false,
        "owner": {
          "login": "Klerith",
          "id": 3438503,
          "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Klerith",
          "html_url": "https://github.com/Klerith",
          "followers_url": "https://api.github.com/users/Klerith/followers",
          "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
          "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
          "organizations_url": "https://api.github.com/users/Klerith/orgs",
          "repos_url": "https://api.github.com/users/Klerith/repos",
          "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Klerith/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Klerith/mas-talento",
        "description": "Repositorio con las hojas de atajo y presentaciones de mis cursos",
        "fork": false,
        "url": "https://api.github.com/repos/Klerith/mas-talento",
        "forks_url": "https://api.github.com/repos/Klerith/mas-talento/forks",
        "keys_url": "https://api.github.com/repos/Klerith/mas-talento/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Klerith/mas-talento/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Klerith/mas-talento/teams",
        "hooks_url": "https://api.github.com/repos/Klerith/mas-talento/hooks",
        "issue_events_url": "https://api.github.com/repos/Klerith/mas-talento/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Klerith/mas-talento/events",
        "assignees_url": "https://api.github.com/repos/Klerith/mas-talento/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Klerith/mas-talento/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Klerith/mas-talento/tags",
        "blobs_url": "https://api.github.com/repos/Klerith/mas-talento/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Klerith/mas-talento/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Klerith/mas-talento/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Klerith/mas-talento/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Klerith/mas-talento/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Klerith/mas-talento/languages",
        "stargazers_url": "https://api.github.com/repos/Klerith/mas-talento/stargazers",
        "contributors_url": "https://api.github.com/repos/Klerith/mas-talento/contributors",
        "subscribers_url": "https://api.github.com/repos/Klerith/mas-talento/subscribers",
        "subscription_url": "https://api.github.com/repos/Klerith/mas-talento/subscription",
        "commits_url": "https://api.github.com/repos/Klerith/mas-talento/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Klerith/mas-talento/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Klerith/mas-talento/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Klerith/mas-talento/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Klerith/mas-talento/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Klerith/mas-talento/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Klerith/mas-talento/merges",
        "archive_url": "https://api.github.com/repos/Klerith/mas-talento/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Klerith/mas-talento/downloads",
        "issues_url": "https://api.github.com/repos/Klerith/mas-talento/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Klerith/mas-talento/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Klerith/mas-talento/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Klerith/mas-talento/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Klerith/mas-talento/labels{/name}",
        "releases_url": "https://api.github.com/repos/Klerith/mas-talento/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Klerith/mas-talento/deployments",
        "created_at": "2023-07-12T17:34:37Z",
        "updated_at": "2024-11-27T21:27:23Z",
        "pushed_at": "2024-06-18T19:42:56Z",
        "git_url": "git://github.com/Klerith/mas-talento.git",
        "ssh_url": "git@github.com:Klerith/mas-talento.git",
        "clone_url": "https://github.com/Klerith/mas-talento.git",
        "svn_url": "https://github.com/Klerith/mas-talento",
        "homepage": null,
        "size": 261381,
        "stargazers_count": 283,
        "watchers_count": 283,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 57,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 57,
        "open_issues": 0,
        "watchers": 283,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 174431734,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNzQ0MzE3MzQ=",
        "name": "curso-VSCode",
        "full_name": "Klerith/curso-VSCode",
        "private": false,
        "owner": {
          "login": "Klerith",
          "id": 3438503,
          "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Klerith",
          "html_url": "https://github.com/Klerith",
          "followers_url": "https://api.github.com/users/Klerith/followers",
          "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
          "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
          "organizations_url": "https://api.github.com/users/Klerith/orgs",
          "repos_url": "https://api.github.com/users/Klerith/repos",
          "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Klerith/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Klerith/curso-VSCode",
        "description": "El repositorio del curso donde trabajaremos para mejorar el uso de VSCode",
        "fork": false,
        "url": "https://api.github.com/repos/Klerith/curso-VSCode",
        "forks_url": "https://api.github.com/repos/Klerith/curso-VSCode/forks",
        "keys_url": "https://api.github.com/repos/Klerith/curso-VSCode/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Klerith/curso-VSCode/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Klerith/curso-VSCode/teams",
        "hooks_url": "https://api.github.com/repos/Klerith/curso-VSCode/hooks",
        "issue_events_url": "https://api.github.com/repos/Klerith/curso-VSCode/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Klerith/curso-VSCode/events",
        "assignees_url": "https://api.github.com/repos/Klerith/curso-VSCode/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Klerith/curso-VSCode/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Klerith/curso-VSCode/tags",
        "blobs_url": "https://api.github.com/repos/Klerith/curso-VSCode/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Klerith/curso-VSCode/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Klerith/curso-VSCode/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Klerith/curso-VSCode/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Klerith/curso-VSCode/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Klerith/curso-VSCode/languages",
        "stargazers_url": "https://api.github.com/repos/Klerith/curso-VSCode/stargazers",
        "contributors_url": "https://api.github.com/repos/Klerith/curso-VSCode/contributors",
        "subscribers_url": "https://api.github.com/repos/Klerith/curso-VSCode/subscribers",
        "subscription_url": "https://api.github.com/repos/Klerith/curso-VSCode/subscription",
        "commits_url": "https://api.github.com/repos/Klerith/curso-VSCode/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Klerith/curso-VSCode/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Klerith/curso-VSCode/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Klerith/curso-VSCode/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Klerith/curso-VSCode/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Klerith/curso-VSCode/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Klerith/curso-VSCode/merges",
        "archive_url": "https://api.github.com/repos/Klerith/curso-VSCode/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Klerith/curso-VSCode/downloads",
        "issues_url": "https://api.github.com/repos/Klerith/curso-VSCode/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Klerith/curso-VSCode/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Klerith/curso-VSCode/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Klerith/curso-VSCode/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Klerith/curso-VSCode/labels{/name}",
        "releases_url": "https://api.github.com/repos/Klerith/curso-VSCode/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Klerith/curso-VSCode/deployments",
        "created_at": "2019-03-07T22:45:32Z",
        "updated_at": "2024-10-01T19:05:42Z",
        "pushed_at": "2022-11-30T21:35:15Z",
        "git_url": "git://github.com/Klerith/curso-VSCode.git",
        "ssh_url": "git@github.com:Klerith/curso-VSCode.git",
        "clone_url": "https://github.com/Klerith/curso-VSCode.git",
        "svn_url": "https://github.com/Klerith/curso-VSCode",
        "homepage": null,
        "size": 169,
        "stargazers_count": 258,
        "watchers_count": 258,
        "language": "CSS",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 257,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 2,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 257,
        "open_issues": 2,
        "watchers": 258,
        "default_branch": "master",
        "score": 1.0
      },
      {
        "id": 179885537,
        "node_id": "MDEwOlJlcG9zaXRvcnkxNzk4ODU1Mzc=",
        "name": "dart-basics",
        "full_name": "Klerith/dart-basics",
        "private": false,
        "owner": {
          "login": "Klerith",
          "id": 3438503,
          "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Klerith",
          "html_url": "https://github.com/Klerith",
          "followers_url": "https://api.github.com/users/Klerith/followers",
          "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
          "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
          "organizations_url": "https://api.github.com/users/Klerith/orgs",
          "repos_url": "https://api.github.com/users/Klerith/repos",
          "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Klerith/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Klerith/dart-basics",
        "description": "Un repositorio con los ejercicios de reforzamiento de Dart para el curso de Flutter",
        "fork": false,
        "url": "https://api.github.com/repos/Klerith/dart-basics",
        "forks_url": "https://api.github.com/repos/Klerith/dart-basics/forks",
        "keys_url": "https://api.github.com/repos/Klerith/dart-basics/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Klerith/dart-basics/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Klerith/dart-basics/teams",
        "hooks_url": "https://api.github.com/repos/Klerith/dart-basics/hooks",
        "issue_events_url": "https://api.github.com/repos/Klerith/dart-basics/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Klerith/dart-basics/events",
        "assignees_url": "https://api.github.com/repos/Klerith/dart-basics/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Klerith/dart-basics/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Klerith/dart-basics/tags",
        "blobs_url": "https://api.github.com/repos/Klerith/dart-basics/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Klerith/dart-basics/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Klerith/dart-basics/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Klerith/dart-basics/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Klerith/dart-basics/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Klerith/dart-basics/languages",
        "stargazers_url": "https://api.github.com/repos/Klerith/dart-basics/stargazers",
        "contributors_url": "https://api.github.com/repos/Klerith/dart-basics/contributors",
        "subscribers_url": "https://api.github.com/repos/Klerith/dart-basics/subscribers",
        "subscription_url": "https://api.github.com/repos/Klerith/dart-basics/subscription",
        "commits_url": "https://api.github.com/repos/Klerith/dart-basics/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Klerith/dart-basics/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Klerith/dart-basics/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Klerith/dart-basics/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Klerith/dart-basics/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Klerith/dart-basics/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Klerith/dart-basics/merges",
        "archive_url": "https://api.github.com/repos/Klerith/dart-basics/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Klerith/dart-basics/downloads",
        "issues_url": "https://api.github.com/repos/Klerith/dart-basics/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Klerith/dart-basics/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Klerith/dart-basics/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Klerith/dart-basics/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Klerith/dart-basics/labels{/name}",
        "releases_url": "https://api.github.com/repos/Klerith/dart-basics/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Klerith/dart-basics/deployments",
        "created_at": "2019-04-06T20:53:23Z",
        "updated_at": "2024-11-14T01:04:01Z",
        "pushed_at": "2023-10-07T17:44:17Z",
        "git_url": "git://github.com/Klerith/dart-basics.git",
        "ssh_url": "git@github.com:Klerith/dart-basics.git",
        "clone_url": "https://github.com/Klerith/dart-basics.git",
        "svn_url": "https://github.com/Klerith/dart-basics",
        "homepage": null,
        "size": 24,
        "stargazers_count": 192,
        "watchers_count": 192,
        "language": "Dart",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 178,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 1,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 178,
        "open_issues": 1,
        "watchers": 192,
        "default_branch": "master",
        "score": 1.0
      },
      {
        "id": 262161694,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNjIxNjE2OTQ=",
        "name": "react-intro-javascript",
        "full_name": "Klerith/react-intro-javascript",
        "private": false,
        "owner": {
          "login": "Klerith",
          "id": 3438503,
          "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Klerith",
          "html_url": "https://github.com/Klerith",
          "followers_url": "https://api.github.com/users/Klerith/followers",
          "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
          "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
          "organizations_url": "https://api.github.com/users/Klerith/orgs",
          "repos_url": "https://api.github.com/users/Klerith/repos",
          "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Klerith/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Klerith/react-intro-javascript",
        "description": "Repositorio con los ejercicios de reforzamiento de JavaScript para React",
        "fork": false,
        "url": "https://api.github.com/repos/Klerith/react-intro-javascript",
        "forks_url": "https://api.github.com/repos/Klerith/react-intro-javascript/forks",
        "keys_url": "https://api.github.com/repos/Klerith/react-intro-javascript/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Klerith/react-intro-javascript/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Klerith/react-intro-javascript/teams",
        "hooks_url": "https://api.github.com/repos/Klerith/react-intro-javascript/hooks",
        "issue_events_url": "https://api.github.com/repos/Klerith/react-intro-javascript/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Klerith/react-intro-javascript/events",
        "assignees_url": "https://api.github.com/repos/Klerith/react-intro-javascript/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Klerith/react-intro-javascript/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Klerith/react-intro-javascript/tags",
        "blobs_url": "https://api.github.com/repos/Klerith/react-intro-javascript/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Klerith/react-intro-javascript/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Klerith/react-intro-javascript/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Klerith/react-intro-javascript/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Klerith/react-intro-javascript/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Klerith/react-intro-javascript/languages",
        "stargazers_url": "https://api.github.com/repos/Klerith/react-intro-javascript/stargazers",
        "contributors_url": "https://api.github.com/repos/Klerith/react-intro-javascript/contributors",
        "subscribers_url": "https://api.github.com/repos/Klerith/react-intro-javascript/subscribers",
        "subscription_url": "https://api.github.com/repos/Klerith/react-intro-javascript/subscription",
        "commits_url": "https://api.github.com/repos/Klerith/react-intro-javascript/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Klerith/react-intro-javascript/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Klerith/react-intro-javascript/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Klerith/react-intro-javascript/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Klerith/react-intro-javascript/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Klerith/react-intro-javascript/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Klerith/react-intro-javascript/merges",
        "archive_url": "https://api.github.com/repos/Klerith/react-intro-javascript/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Klerith/react-intro-javascript/downloads",
        "issues_url": "https://api.github.com/repos/Klerith/react-intro-javascript/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Klerith/react-intro-javascript/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Klerith/react-intro-javascript/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Klerith/react-intro-javascript/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Klerith/react-intro-javascript/labels{/name}",
        "releases_url": "https://api.github.com/repos/Klerith/react-intro-javascript/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Klerith/react-intro-javascript/deployments",
        "created_at": "2020-05-07T21:24:30Z",
        "updated_at": "2024-11-24T14:49:54Z",
        "pushed_at": "2023-01-05T20:02:58Z",
        "git_url": "git://github.com/Klerith/react-intro-javascript.git",
        "ssh_url": "git@github.com:Klerith/react-intro-javascript.git",
        "clone_url": "https://github.com/Klerith/react-intro-javascript.git",
        "svn_url": "https://github.com/Klerith/react-intro-javascript",
        "homepage": null,
        "size": 4263,
        "stargazers_count": 153,
        "watchers_count": 153,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 121,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 22,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 121,
        "open_issues": 22,
        "watchers": 153,
        "default_branch": "master",
        "score": 1.0
      },
      {
        "id": 471731348,
        "node_id": "R_kgDOHB4MlA",
        "name": "clean-course",
        "full_name": "Klerith/clean-course",
        "private": false,
        "owner": {
          "login": "Klerith",
          "id": 3438503,
          "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Klerith",
          "html_url": "https://github.com/Klerith",
          "followers_url": "https://api.github.com/users/Klerith/followers",
          "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
          "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
          "organizations_url": "https://api.github.com/users/Klerith/orgs",
          "repos_url": "https://api.github.com/users/Klerith/repos",
          "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Klerith/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Klerith/clean-course",
        "description": "Repositorio del proyecto de Clean & SOLID - Curso",
        "fork": false,
        "url": "https://api.github.com/repos/Klerith/clean-course",
        "forks_url": "https://api.github.com/repos/Klerith/clean-course/forks",
        "keys_url": "https://api.github.com/repos/Klerith/clean-course/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Klerith/clean-course/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Klerith/clean-course/teams",
        "hooks_url": "https://api.github.com/repos/Klerith/clean-course/hooks",
        "issue_events_url": "https://api.github.com/repos/Klerith/clean-course/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Klerith/clean-course/events",
        "assignees_url": "https://api.github.com/repos/Klerith/clean-course/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Klerith/clean-course/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Klerith/clean-course/tags",
        "blobs_url": "https://api.github.com/repos/Klerith/clean-course/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Klerith/clean-course/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Klerith/clean-course/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Klerith/clean-course/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Klerith/clean-course/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Klerith/clean-course/languages",
        "stargazers_url": "https://api.github.com/repos/Klerith/clean-course/stargazers",
        "contributors_url": "https://api.github.com/repos/Klerith/clean-course/contributors",
        "subscribers_url": "https://api.github.com/repos/Klerith/clean-course/subscribers",
        "subscription_url": "https://api.github.com/repos/Klerith/clean-course/subscription",
        "commits_url": "https://api.github.com/repos/Klerith/clean-course/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Klerith/clean-course/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Klerith/clean-course/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Klerith/clean-course/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Klerith/clean-course/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Klerith/clean-course/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Klerith/clean-course/merges",
        "archive_url": "https://api.github.com/repos/Klerith/clean-course/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Klerith/clean-course/downloads",
        "issues_url": "https://api.github.com/repos/Klerith/clean-course/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Klerith/clean-course/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Klerith/clean-course/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Klerith/clean-course/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Klerith/clean-course/labels{/name}",
        "releases_url": "https://api.github.com/repos/Klerith/clean-course/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Klerith/clean-course/deployments",
        "created_at": "2022-03-19T15:12:44Z",
        "updated_at": "2024-11-21T16:39:42Z",
        "pushed_at": "2024-06-05T05:22:13Z",
        "git_url": "git://github.com/Klerith/clean-course.git",
        "ssh_url": "git@github.com:Klerith/clean-course.git",
        "clone_url": "https://github.com/Klerith/clean-course.git",
        "svn_url": "https://github.com/Klerith/clean-course",
        "homepage": null,
        "size": 24,
        "stargazers_count": 125,
        "watchers_count": 125,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 751,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 7,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 751,
        "open_issues": 7,
        "watchers": 125,
        "default_branch": "main",
        "score": 1.0
      },
      {
        "id": 212621703,
        "node_id": "MDEwOlJlcG9zaXRvcnkyMTI2MjE3MDM=",
        "name": "archivos-del-mes",
        "full_name": "Klerith/archivos-del-mes",
        "private": false,
        "owner": {
          "login": "Klerith",
          "id": 3438503,
          "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Klerith",
          "html_url": "https://github.com/Klerith",
          "followers_url": "https://api.github.com/users/Klerith/followers",
          "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
          "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
          "organizations_url": "https://api.github.com/users/Klerith/orgs",
          "repos_url": "https://api.github.com/users/Klerith/repos",
          "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Klerith/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Klerith/archivos-del-mes",
        "description": "Este es el repositorio donde están todos los archivos gratuitos que brindo en mi sitio web",
        "fork": false,
        "url": "https://api.github.com/repos/Klerith/archivos-del-mes",
        "forks_url": "https://api.github.com/repos/Klerith/archivos-del-mes/forks",
        "keys_url": "https://api.github.com/repos/Klerith/archivos-del-mes/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Klerith/archivos-del-mes/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Klerith/archivos-del-mes/teams",
        "hooks_url": "https://api.github.com/repos/Klerith/archivos-del-mes/hooks",
        "issue_events_url": "https://api.github.com/repos/Klerith/archivos-del-mes/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Klerith/archivos-del-mes/events",
        "assignees_url": "https://api.github.com/repos/Klerith/archivos-del-mes/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Klerith/archivos-del-mes/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Klerith/archivos-del-mes/tags",
        "blobs_url": "https://api.github.com/repos/Klerith/archivos-del-mes/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Klerith/archivos-del-mes/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Klerith/archivos-del-mes/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Klerith/archivos-del-mes/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Klerith/archivos-del-mes/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Klerith/archivos-del-mes/languages",
        "stargazers_url": "https://api.github.com/repos/Klerith/archivos-del-mes/stargazers",
        "contributors_url": "https://api.github.com/repos/Klerith/archivos-del-mes/contributors",
        "subscribers_url": "https://api.github.com/repos/Klerith/archivos-del-mes/subscribers",
        "subscription_url": "https://api.github.com/repos/Klerith/archivos-del-mes/subscription",
        "commits_url": "https://api.github.com/repos/Klerith/archivos-del-mes/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Klerith/archivos-del-mes/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Klerith/archivos-del-mes/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Klerith/archivos-del-mes/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Klerith/archivos-del-mes/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Klerith/archivos-del-mes/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Klerith/archivos-del-mes/merges",
        "archive_url": "https://api.github.com/repos/Klerith/archivos-del-mes/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Klerith/archivos-del-mes/downloads",
        "issues_url": "https://api.github.com/repos/Klerith/archivos-del-mes/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Klerith/archivos-del-mes/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Klerith/archivos-del-mes/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Klerith/archivos-del-mes/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Klerith/archivos-del-mes/labels{/name}",
        "releases_url": "https://api.github.com/repos/Klerith/archivos-del-mes/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Klerith/archivos-del-mes/deployments",
        "created_at": "2019-10-03T16:05:32Z",
        "updated_at": "2024-07-14T23:45:44Z",
        "pushed_at": "2020-02-05T16:44:03Z",
        "git_url": "git://github.com/Klerith/archivos-del-mes.git",
        "ssh_url": "git@github.com:Klerith/archivos-del-mes.git",
        "clone_url": "https://github.com/Klerith/archivos-del-mes.git",
        "svn_url": "https://github.com/Klerith/archivos-del-mes",
        "homepage": null,
        "size": 389946,
        "stargazers_count": 122,
        "watchers_count": 122,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 51,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 51,
        "open_issues": 0,
        "watchers": 122,
        "default_branch": "master",
        "score": 1.0
      },
      {
        "id": 488963219,
        "node_id": "R_kgDOHST8kw",
        "name": "custom-hooks",
        "full_name": "Klerith/custom-hooks",
        "private": false,
        "owner": {
          "login": "Klerith",
          "id": 3438503,
          "node_id": "MDQ6VXNlcjM0Mzg1MDM=",
          "avatar_url": "https://avatars.githubusercontent.com/u/3438503?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Klerith",
          "html_url": "https://github.com/Klerith",
          "followers_url": "https://api.github.com/users/Klerith/followers",
          "following_url": "https://api.github.com/users/Klerith/following{/other_user}",
          "gists_url": "https://api.github.com/users/Klerith/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Klerith/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Klerith/subscriptions",
          "organizations_url": "https://api.github.com/users/Klerith/orgs",
          "repos_url": "https://api.github.com/users/Klerith/repos",
          "events_url": "https://api.github.com/users/Klerith/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Klerith/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "html_url": "https://github.com/Klerith/custom-hooks",
        "description": "Este es un pequeño repositorio con mis custom hooks",
        "fork": false,
        "url": "https://api.github.com/repos/Klerith/custom-hooks",
        "forks_url": "https://api.github.com/repos/Klerith/custom-hooks/forks",
        "keys_url": "https://api.github.com/repos/Klerith/custom-hooks/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Klerith/custom-hooks/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Klerith/custom-hooks/teams",
        "hooks_url": "https://api.github.com/repos/Klerith/custom-hooks/hooks",
        "issue_events_url": "https://api.github.com/repos/Klerith/custom-hooks/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Klerith/custom-hooks/events",
        "assignees_url": "https://api.github.com/repos/Klerith/custom-hooks/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Klerith/custom-hooks/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Klerith/custom-hooks/tags",
        "blobs_url": "https://api.github.com/repos/Klerith/custom-hooks/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Klerith/custom-hooks/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Klerith/custom-hooks/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Klerith/custom-hooks/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Klerith/custom-hooks/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Klerith/custom-hooks/languages",
        "stargazers_url": "https://api.github.com/repos/Klerith/custom-hooks/stargazers",
        "contributors_url": "https://api.github.com/repos/Klerith/custom-hooks/contributors",
        "subscribers_url": "https://api.github.com/repos/Klerith/custom-hooks/subscribers",
        "subscription_url": "https://api.github.com/repos/Klerith/custom-hooks/subscription",
        "commits_url": "https://api.github.com/repos/Klerith/custom-hooks/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Klerith/custom-hooks/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Klerith/custom-hooks/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Klerith/custom-hooks/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Klerith/custom-hooks/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Klerith/custom-hooks/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Klerith/custom-hooks/merges",
        "archive_url": "https://api.github.com/repos/Klerith/custom-hooks/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Klerith/custom-hooks/downloads",
        "issues_url": "https://api.github.com/repos/Klerith/custom-hooks/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Klerith/custom-hooks/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Klerith/custom-hooks/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Klerith/custom-hooks/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Klerith/custom-hooks/labels{/name}",
        "releases_url": "https://api.github.com/repos/Klerith/custom-hooks/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Klerith/custom-hooks/deployments",
        "created_at": "2022-05-05T12:28:01Z",
        "updated_at": "2024-11-28T04:05:40Z",
        "pushed_at": "2022-05-05T12:33:42Z",
        "git_url": "git://github.com/Klerith/custom-hooks.git",
        "ssh_url": "git@github.com:Klerith/custom-hooks.git",
        "clone_url": "https://github.com/Klerith/custom-hooks.git",
        "svn_url": "https://github.com/Klerith/custom-hooks",
        "homepage": null,
        "size": 3,
        "stargazers_count": 115,
        "watchers_count": 115,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 87,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 87,
        "open_issues": 0,
        "watchers": 115,
        "default_branch": "main",
        "score": 1.0
      }
    ]
  };

  constructor(){

  }

  public loadRepositories(params: any): Observable<Item[]> {

    let query = `user:${params.userName}`;
    if (params.repository) {
      query += `+${params.repository}`;
    }
    if (params.language) {
      query += `+language:${params.language}`;
    }

    const pageOrder = `page=${params.page}&per_page=8&sort=${params.sort}&order=desc`;
    const url = `${this.API}/search/repositories?q=${query}&${pageOrder}`;
    console.log(url);
    return this.http.get<GithubRepositoriesResponse>(url)
    .pipe(
      map(repo => repo.items),
      catchError((error)=>{
        return throwError(()=> new Error(error));
      })
    )

    // return new Observable<GithubRepositoriesResponse>((subs) => {
    //   subs.next(this.fakeRepositoriesResponse);
    //   subs.complete();
    // }).pipe(
    //   map(repo => repo.items),
    //   catchError((error) => {
    //     return of([]);
    //   })
    // )


  }

  public loadUser(userName:string): Observable<User | null> {

    // return new Observable<GithubUserResponse>((subs) => {
    //   //subs.error(this.fakeUserResponseError);
    //   subs.next(this.fakeUserResponse);
    //   subs.complete();
    // }).pipe(
    //   map(({
    //     login, id, avatar_url, html_url, repos_url, events_url,
    //     received_events_url, name, company, blog,
    //     location, bio, twitter_username, public_repos
    //   }) => ({
    //     login, id, avatar_url, html_url, repos_url, events_url,
    //     received_events_url, name, company, blog,
    //     location, bio, twitter_username, public_repos
    //   })),

    //   catchError((error) => {
    //    // console.error(error)
    //     return of(null)
    //   })
    // )

    return this.http.get<GithubUserResponse>(`${this.API}/users/${userName}`)
      .pipe(
        map(({
          login, id, avatar_url, html_url, repos_url, events_url,
          received_events_url, name, company, blog,
          location, bio, twitter_username, public_repos
        }) => ({
          login, id, avatar_url, html_url, repos_url, events_url,
          received_events_url, name, company, blog,
          location, bio, twitter_username, public_repos
        })
        ),
        catchError((error) => {
          return of(null)
        })
      );
  }
}
